name: Build and Push dev MCAD image into Quay

on:
  push:
    branches:
      - '*'
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
